name = "lanzou-direct-link"
main = "worker.js"
compatibility_date = "2025-08-21"

[build]
command = ""

[vars]
# BATCH_SIZE = "5"  # 批处理大小，用于控制批量操作的批次大小
# REFRESH_INTERVAL = "720000"  # 12分钟 (毫秒)
# URGENT_THRESHOLD = "180000"  # 3分钟 (毫秒)
# MAX_KEYS_TO_PROCESS = "50"

[triggers]
crons = ["*/12 * * * *"] # 每12分钟执行一次，与链接有效期匹配

# 配置自定义域名，只启用 dir.gjqqq.com
[[routes]]
pattern = "dir.gjqqq.com"
custom_domain = true

[[kv_namespaces]]
binding = "DOWNLOAD_CACHE"
id = "9e6cde26fb8c45adb1f1771a00c6a375"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "lanzou_cache"
database_id = "ccb64416-6262-469a-b7ab-d9d3c53f0f6a"