name: Refresh Download Links

on:
  schedule:
    # 每12分钟运行一次，与缓存刷新间隔保持一致
    - cron: '*/12 * * * *'
  workflow_dispatch: # 允许手动触发
  # 添加push事件触发，便于调试
  push:
    branches:
      - main
    paths:
      - '.github/workflows/refresh-links.yml'
      - 'worker.js'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub Actions environment
        run: |
          echo "Current time: $(date)"
          echo "GitHub repository: ${{ github.repository }}"
          echo "GitHub event name: ${{ github.event_name }}"
          echo "GitHub SHA: ${{ github.sha }}"
          echo "GitHub ref: ${{ github.ref }}"
          
      - name: Debug cron schedule
        run: |
          echo "If this workflow was triggered by cron, check if it's working properly."
          echo "Last commit time: $(git log -1 --format='%cd')"
          
      - name: Call refresh API with retry mechanism
        run: |
          # 检查是否设置了REFRESH_URL
          if [ -z "${{ secrets.REFRESH_URL }}" ]; then
            echo "Error: REFRESH_URL secret is not set"
            echo "Please set the REFRESH_URL secret in your repository settings"
            echo "The value should be: https://lanzou-direct-link.wovow.workers.dev/refresh"
            echo "You can set it at: https://github.com/${{ github.repository }}/settings/secrets/actions"
            exit 1
          fi
          
          echo "Calling refresh API at: ${{ secrets.REFRESH_URL }}"
          
          # 添加时间戳用于跟踪执行
          echo "Execution timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          
          # 添加重试机制
          max_retries=3
          retry_count=0
          success=false
          
          while [ $retry_count -lt $max_retries ] && [ "$success" = false ]; do
            # 使用curl调用刷新接口，设置超时时间
            response=$(curl -s -w "\n%{http_code}" -X GET "${{ secrets.REFRESH_URL }}" --max-time 30)
            
            # 提取响应体和状态码
            http_code=$(echo "$response" | tail -n1)
            body=$(echo "$response" | sed '$d')
            
            echo "Attempt $((retry_count+1)) - Response body: $body"
            echo "Attempt $((retry_count+1)) - HTTP status code: $http_code"
            
            # 检查HTTP状态码，如果是2xx则标记为成功
            if [[ $http_code -ge 200 && $http_code -lt 300 ]]; then
              echo "Refresh task completed successfully on attempt $((retry_count+1))"
              echo "Success timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
              success=true
            else
              echo "Attempt $((retry_count+1)) failed with status code $http_code"
              retry_count=$((retry_count+1))
              
              # 如果还没达到最大重试次数，则等待一段时间后重试
              if [ $retry_count -lt $max_retries ]; then
                sleep_time=$((retry_count * 30))  # 逐步增加等待时间
                echo "Waiting ${sleep_time}s before retry..."
                sleep $sleep_time
              fi
            fi
          done
          
          # 如果所有重试都失败了，则退出并标记为失败
          if [ "$success" = false ]; then
            echo "Error: Request failed after $max_retries attempts"
            echo "Last response body: $body"
            echo "Last HTTP status code: $http_code"
            echo "Failure timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
            exit 1
          fi